# Generated by Django 3.0.7 on 2020-08-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20200716_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='touch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('sunject', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
