# Generated by Django 3.0.7 on 2020-08-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20200816_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='message',
            field=models.TextField(),
        ),
    ]
