# Generated by Django 3.0.7 on 2020-08-17 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_auto_20200816_1643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feed',
        ),
    ]
